version: '3.7'
services:
  postgres:
    image: postgres:15rc2
    restart: always
    environment:
      - POSTGRES_DB=ziplink
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  ziplink:
    image: ziplink:latest
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - '8080:8080'
    depends_on:
      - postgres